### ISSUE TITLE
Seens like ApiModelProperty addition trips up the html generator

### ISSUE THREAD

**Issue by hum2u** [chenjianjx/swagger2html#7]
I get out of memory error. No amount of heap increase helps

-Xms2048m
-Xmx4096m
-XX:MaxPermSize=12800m

the above is the current setting

test case 1 : about 25 REST services without any ApiModelProperty annotation for any service ===> generate HTML successfully

test case 2 : Same as test case 1, but one single service updated with several ApiModelProperty annotations for a multiply used response class (response class is the response for several of the service class methods) bean properties ===> HTML generation fails with OOM error, no amount of memory addition helps

=====================================================

reading from C:\Users\bnemazie\temp\s2h-test\swagger.json
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 13.229 sec <<< FAILURE!
toHtmlTestSwagger(org.swagger2html.Swagger2HtmlTest)  Time elapsed: 11.95 sec  <<< ERROR!
java.lang.OutOfMemoryError: Java heap space
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:280)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)
	at org.swagger2html.Swagger2Html.modelPropertiesToRows(Swagger2Html.java:317)

**Comment by chenjianjx** [comment]
hi, thank you for the bug report.  Is it possible for you to upload your swagger.json?  or you can send a private message to me for that.

**Comment by hum2u** [comment]
I tied to make a sample to avoid divulging company info, but could not reproduce.

The problem seems to be due to response class being a class with multiply nested classes as its ref properties.

The debugger execution shows the problem is with StackOverflow exception rather than with OOM error. This is why it is failing no matter what the min/max/heap memory settings are.

Problem is due to recursive call in the method modelPropertiesToRows below:

	private void modelPropertiesToRows(Map<String, Property> properties,
			Swagger swagger, String parentPath, List<ModelRow> rows) {

		if (properties == null) {
			return;
		}

		for (Map.Entry<String, Property> entry : properties.entrySet()) {
			String ognlPath = parentPath == null ? entry.getKey() : (parentPath
					+ "." + entry.getKey());
			Property property = entry.getValue();
			String type = propertyTypeString(property);

			if (property instanceof ArrayProperty) {
				ognlPath = ognlPath + "[]";
				ModelRow row = new ModelRow();
				row.setOgnlPath(ognlPath);
				row.setProperty(property);
				row.setTypeStr(type);
				rows.add(row);

				Property itemProperty = ((ArrayProperty) property).getItems();

				if (isPropertyRefType(swagger, itemProperty)) {
					Model model = swagger.getDefinitions().get(
							propertyTypeString(itemProperty));
					Map<String, Property> childProperties = model
							.getProperties();
					modelPropertiesToRows(childProperties, swagger, ognlPath,
							rows);

				}
				continue;

			}

			ModelRow row = new ModelRow();
			row.setOgnlPath(ognlPath);
			row.setProperty(property);
			row.setTypeStr(type);
			rows.add(row);

			if (isPropertyRefType(swagger, property) && type != null) {
				Model model = swagger.getDefinitions().get(type);
				Map<String, Property> childProperties = model.getProperties();
				**modelPropertiesToRows(childProperties, swagger, ognlPath, rows);**
			}
			continue;
		}

	}

see the row in bold above, where the recursive call is made.

**Comment by chenjianjx** [comment]
Ok,  I'll investigate it in a few days.

**Comment by chenjianjx** [comment]
hi,  @hum2u , I fixed it in branch:  https://github.com/chenjianjx/swagger2html/tree/recurrsion-problem  

Do you want to test it before I merge it to master?    You can clone the source, check out to this branch,  do a "mvn clean install",  and use version "2.0.1-SNAPSHOT" in your own project.  

If things work well for you I'll do the merge and create version 2.0.1

**Comment by chenjianjx** [comment]
Fixed in version 2.0.1

**Comment by hum2u** [comment]
Hi , 

I tried your solution,I got an NPE.  I sent an email response, but just in case you did not see it or have not see it yet the 2 lines in your code fix after the model retrieval below 

Map<String, Property> childProperties = model
						.getProperties();

should be in an if(model !=null) if condition to prevent NPE. Once I added the null check, html generation worked fine

Thanks

**Comment by chenjianjx** [comment]
@hum2u , can you submit a pull request for this? If you have time to do it,  please make the POM version 2.0.2 in your PR. 

Let me know if you prefer I do it.
